package orm

import "github.com/tinywasm/fmt"

// Model represents a database model.
// It extends fmt.Fielder with a table name for database operations.
// Implementations are generated by ormc.
type Model interface {
	fmt.Fielder
	TableName() string
}
