package orm

import "github.com/tinywasm/fmt"

// Model represents a database model.
// It extends fmt.Fielder (Schema() + Pointers()) with a table name.
// Implementations are generated by ormc.
type Model interface {
	fmt.Fielder
	TableName() string
}
