//go:build !wasm

package orm

import (
	"os"

	"github.com/tinywasm/fmt"
)

// GenerateForFile writes ORM implementations for all infos into one file.
func (o *Ormc) GenerateForFile(infos []StructInfo, sourceFile string) error {
	if len(infos) == 0 {
		return nil
	}
	buf := fmt.Convert()

	// File Header
	buf.Write(fmt.Sprintf("// DO NOT EDIT. generated by github.com/tinywasm/orm\n\n"))
	buf.Write(fmt.Sprintf("package %s\n\n", infos[0].PackageName))

	hasModel := false
	hasWidget := false
	for _, info := range infos {
		if !info.FormOnly {
			hasModel = true
		}
		for _, f := range info.Fields {
			if f.WidgetConstructor != "" {
				hasWidget = true
			}
		}
	}

	buf.Write("import (\n")
	buf.Write("\t\"github.com/tinywasm/fmt\"\n")
	if hasModel {
		buf.Write("\t\"github.com/tinywasm/orm\"\n")
	}
	if hasWidget {
		buf.Write("\t\"github.com/tinywasm/form/input\"\n")
	}
	buf.Write(")\n\n")

	for _, info := range infos {
		if !info.FormOnly {
			// Model Interface Methods
			if !info.ModelNameDeclared {
				buf.Write(fmt.Sprintf("func (m *%s) ModelName() string {\n", info.Name))
				buf.Write(fmt.Sprintf("\treturn \"%s\"\n", info.ModelName))
				buf.Write("}\n\n")
			}
		}

		buf.Write(fmt.Sprintf("var _schema%s = []fmt.Field{\n", info.Name))
		for _, f := range info.Fields {
			typeStr := "fmt.FieldText"
			switch f.Type {
			case fmt.FieldInt:
				typeStr = "fmt.FieldInt"
			case fmt.FieldFloat:
				typeStr = "fmt.FieldFloat"
			case fmt.FieldBool:
				typeStr = "fmt.FieldBool"
			case fmt.FieldBlob:
				typeStr = "fmt.FieldBlob"
			case fmt.FieldStruct:
				typeStr = "fmt.FieldStruct"
			}

			buf.Write(fmt.Sprintf("\t\t{Name: \"%s\", Type: %s", f.ColumnName, typeStr))
			if !info.FormOnly && (f.PK || f.Unique || f.AutoInc) {
				buf.Write(", DB: &fmt.FieldDB{")
				var parts []string
				if f.PK {
					parts = append(parts, "PK: true")
				}
				if f.Unique {
					parts = append(parts, "Unique: true")
				}
				if f.AutoInc {
					parts = append(parts, "AutoInc: true")
				}
				buf.Write(fmt.Convert(parts).Join(", ").String())
				buf.Write("}")
			}
			if f.NotNull {
				buf.Write(", NotNull: true")
			}
			if f.OmitEmpty {
				buf.Write(", OmitEmpty: true")
			}
			if f.WidgetConstructor != "" {
				buf.Write(fmt.Sprintf(", Widget: %s", f.WidgetConstructor))
			}
			writePermittedFields(buf, f)
			buf.Write("},\n")
		}
		buf.Write("\t}\n\n")

		buf.Write(fmt.Sprintf("func (m *%s) Schema() []fmt.Field { return _schema%s }\n\n", info.Name, info.Name))

		buf.Write(fmt.Sprintf("func (m *%s) Pointers() []any {\n", info.Name))
		buf.Write("\treturn []any{\n")
		for _, f := range info.Fields {
			buf.Write(fmt.Sprintf("\t\t&m.%s,\n", f.Name))
		}
		buf.Write("\t}\n")
		buf.Write("}\n\n")

		hasValidation := info.IsForm
		if !hasValidation {
			for _, f := range info.Fields {
				if f.NotNull || f.Letters || f.Numbers || f.Tilde || f.Spaces ||
					len(f.Extra) > 0 || f.Minimum > 0 || f.Maximum > 0 {
					hasValidation = true
					break
				}
			}
		}

		if hasValidation {
			buf.Write(fmt.Sprintf("func (m *%s) Validate(action byte) error {\n", info.Name))
			buf.Write("\treturn fmt.ValidateFields(action, m)\n")
			buf.Write("}\n\n")
		}

		if !info.FormOnly {
			// Metadata Descriptors
			buf.Write(fmt.Sprintf("var %s_ = struct {\n", info.Name))
			for _, f := range info.Fields {
				buf.Write(fmt.Sprintf("\t%s string\n", f.Name))
			}
			buf.Write("}{\n")
			for _, f := range info.Fields {
				buf.Write(fmt.Sprintf("\t%s: \"%s\",\n", f.Name, f.ColumnName))
			}
			buf.Write("}\n\n")

			// Typed Read Operations
			buf.Write(fmt.Sprintf("func ReadOne%s(qb *orm.QB, model *%s) (*%s, error) {\n", info.Name, info.Name, info.Name))
			buf.Write("\terr := qb.ReadOne()\n")
			buf.Write("\tif err != nil {\n")
			buf.Write("\t\treturn nil, err\n")
			buf.Write("\t}\n")
			buf.Write("\treturn model, nil\n")
			buf.Write("}\n\n")

			buf.Write(fmt.Sprintf("func ReadAll%s(qb *orm.QB) ([]*%s, error) {\n", info.Name, info.Name))
			buf.Write(fmt.Sprintf("\tvar results []*%s\n", info.Name))
			buf.Write("\terr := qb.ReadAll(\n")
			buf.Write(fmt.Sprintf("\t\tfunc() fmt.Model { return &%s{} },\n", info.Name))
			buf.Write(fmt.Sprintf("\t\tfunc(m fmt.Model) { results = append(results, m.(*%s)) },\n", info.Name))
			buf.Write("\t)\n")
			buf.Write("\treturn results, err\n")
			buf.Write("}\n\n")

			for _, rel := range info.Relations {
				buf.Write(fmt.Sprintf(
					"// ReadAll%sByParentID retrieves all %s records for a given parent ID.\n"+
						"// Auto-generated by ormc — relation detected via db:\"ref=%s\".\n"+
						"func ReadAll%sBy%s(db *orm.DB, parentID %s) ([]*%s, error) {\n"+
						"\treturn ReadAll%s(db.Query(&%s{}).Where(%s_.%s).Eq(parentID))\n"+
						"}\n\n",
					rel.ChildStruct,
					rel.ChildStruct,
					info.ModelName, // parent table, for the comment
					rel.ChildStruct, rel.FKField, rel.FKFieldType,
					rel.ChildStruct,
					rel.ChildStruct, rel.ChildStruct, rel.ChildStruct, rel.FKField,
				))
			}
		}
	}

	outName := fmt.Convert(sourceFile).TrimSuffix(".go").String() + "_orm.go"
	return os.WriteFile(outName, buf.Bytes(), 0644)
}
