// DO NOT EDIT. generated by github.com/tinywasm/orm

package tests

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
	"github.com/tinywasm/form/input"
)

func (m *User) ModelName() string {
	return "user"
}

var _schemaUser = []fmt.Field{
		{Name: "id", Type: fmt.FieldInt, DB: &fmt.FieldDB{PK: true}},
		{Name: "first_name", Type: fmt.FieldText, NotNull: true},
		{Name: "last_name", Type: fmt.FieldText},
		{Name: "email", Type: fmt.FieldText, DB: &fmt.FieldDB{Unique: true}},
		{Name: "score", Type: fmt.FieldFloat},
		{Name: "is_active", Type: fmt.FieldBool},
		{Name: "avatar", Type: fmt.FieldBlob},
	}

func (m *User) Schema() []fmt.Field { return _schemaUser }

func (m *User) Pointers() []any { return []any{&m.ID, &m.FirstName, &m.LastName, &m.Email, &m.Score, &m.IsActive, &m.Avatar} }

type UserList []*User

func (s *UserList) Schema() []fmt.Field { return nil }
func (s *UserList) Pointers() []any     { return nil }
func (s *UserList) Len() int             { return len(*s) }
func (s *UserList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *UserList) Append() fmt.Fielder  { v := &User{}; *s = append(*s, v); return v }

func (m *User) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func ReadOneUser(qb *orm.QB, model *User) (*User, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUser(qb *orm.QB) (*UserList, error) {
	var results UserList
	err := qb.ReadAll(
		func() fmt.Model { return &User{} },
		func(m fmt.Model) { results = append(results, m.(*User)) },
	)
	return &results, err
}

func (m *Order) ModelName() string {
	return "order"
}

var _schemaOrder = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "user_id", Type: fmt.FieldInt},
		{Name: "total", Type: fmt.FieldFloat},
	}

func (m *Order) Schema() []fmt.Field { return _schemaOrder }

func (m *Order) Pointers() []any { return []any{&m.ID, &m.UserID, &m.Total} }

type OrderList []*Order

func (s *OrderList) Schema() []fmt.Field { return nil }
func (s *OrderList) Pointers() []any     { return nil }
func (s *OrderList) Len() int             { return len(*s) }
func (s *OrderList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *OrderList) Append() fmt.Fielder  { v := &Order{}; *s = append(*s, v); return v }

func ReadOneOrder(qb *orm.QB, model *Order) (*Order, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllOrder(qb *orm.QB) (*OrderList, error) {
	var results OrderList
	err := qb.ReadAll(
		func() fmt.Model { return &Order{} },
		func(m fmt.Model) { results = append(results, m.(*Order)) },
	)
	return &results, err
}

func (m *BadTimeNoTag) ModelName() string {
	return "bad_time_no_tag"
}

var _schemaBadTimeNoTag = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "name", Type: fmt.FieldText},
	}

func (m *BadTimeNoTag) Schema() []fmt.Field { return _schemaBadTimeNoTag }

func (m *BadTimeNoTag) Pointers() []any { return []any{&m.ID, &m.Name} }

type BadTimeNoTagList []*BadTimeNoTag

func (s *BadTimeNoTagList) Schema() []fmt.Field { return nil }
func (s *BadTimeNoTagList) Pointers() []any     { return nil }
func (s *BadTimeNoTagList) Len() int             { return len(*s) }
func (s *BadTimeNoTagList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *BadTimeNoTagList) Append() fmt.Fielder  { v := &BadTimeNoTag{}; *s = append(*s, v); return v }

func ReadOneBadTimeNoTag(qb *orm.QB, model *BadTimeNoTag) (*BadTimeNoTag, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllBadTimeNoTag(qb *orm.QB) (*BadTimeNoTagList, error) {
	var results BadTimeNoTagList
	err := qb.ReadAll(
		func() fmt.Model { return &BadTimeNoTag{} },
		func(m fmt.Model) { results = append(results, m.(*BadTimeNoTag)) },
	)
	return &results, err
}

func (m *ModelWithIgnored) ModelName() string {
	return "model_with_ignored"
}

var _schemaModelWithIgnored = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "name", Type: fmt.FieldText},
		{Name: "score", Type: fmt.FieldFloat},
	}

func (m *ModelWithIgnored) Schema() []fmt.Field { return _schemaModelWithIgnored }

func (m *ModelWithIgnored) Pointers() []any { return []any{&m.ID, &m.Name, &m.Score} }

type ModelWithIgnoredList []*ModelWithIgnored

func (s *ModelWithIgnoredList) Schema() []fmt.Field { return nil }
func (s *ModelWithIgnoredList) Pointers() []any     { return nil }
func (s *ModelWithIgnoredList) Len() int             { return len(*s) }
func (s *ModelWithIgnoredList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *ModelWithIgnoredList) Append() fmt.Fielder  { v := &ModelWithIgnored{}; *s = append(*s, v); return v }

func ReadOneModelWithIgnored(qb *orm.QB, model *ModelWithIgnored) (*ModelWithIgnored, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllModelWithIgnored(qb *orm.QB) (*ModelWithIgnoredList, error) {
	var results ModelWithIgnoredList
	err := qb.ReadAll(
		func() fmt.Model { return &ModelWithIgnored{} },
		func(m fmt.Model) { results = append(results, m.(*ModelWithIgnored)) },
	)
	return &results, err
}

var _schemaMultiA = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "name", Type: fmt.FieldText},
	}

func (m *MultiA) Schema() []fmt.Field { return _schemaMultiA }

func (m *MultiA) Pointers() []any { return []any{&m.ID, &m.Name} }

type MultiAList []*MultiA

func (s *MultiAList) Schema() []fmt.Field { return nil }
func (s *MultiAList) Pointers() []any     { return nil }
func (s *MultiAList) Len() int             { return len(*s) }
func (s *MultiAList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *MultiAList) Append() fmt.Fielder  { v := &MultiA{}; *s = append(*s, v); return v }

func ReadOneMultiA(qb *orm.QB, model *MultiA) (*MultiA, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMultiA(qb *orm.QB) (*MultiAList, error) {
	var results MultiAList
	err := qb.ReadAll(
		func() fmt.Model { return &MultiA{} },
		func(m fmt.Model) { results = append(results, m.(*MultiA)) },
	)
	return &results, err
}

func (m *MultiB) ModelName() string {
	return "multi_b"
}

var _schemaMultiB = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "value", Type: fmt.FieldInt},
	}

func (m *MultiB) Schema() []fmt.Field { return _schemaMultiB }

func (m *MultiB) Pointers() []any { return []any{&m.ID, &m.Value} }

type MultiBList []*MultiB

func (s *MultiBList) Schema() []fmt.Field { return nil }
func (s *MultiBList) Pointers() []any     { return nil }
func (s *MultiBList) Len() int             { return len(*s) }
func (s *MultiBList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *MultiBList) Append() fmt.Fielder  { v := &MultiB{}; *s = append(*s, v); return v }

func ReadOneMultiB(qb *orm.QB, model *MultiB) (*MultiB, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMultiB(qb *orm.QB) (*MultiBList, error) {
	var results MultiBList
	err := qb.ReadAll(
		func() fmt.Model { return &MultiB{} },
		func(m fmt.Model) { results = append(results, m.(*MultiB)) },
	)
	return &results, err
}

func (m *NumericTypes) ModelName() string {
	return "numeric_types"
}

var _schemaNumericTypes = []fmt.Field{
		{Name: "idnumeric", Type: fmt.FieldInt, DB: &fmt.FieldDB{PK: true}, NotNull: true},
		{Name: "count_uint", Type: fmt.FieldInt},
		{Name: "ratio_f32", Type: fmt.FieldFloat},
	}

func (m *NumericTypes) Schema() []fmt.Field { return _schemaNumericTypes }

func (m *NumericTypes) Pointers() []any { return []any{&m.IDNumeric, &m.CountUint, &m.RatioF32} }

type NumericTypesList []*NumericTypes

func (s *NumericTypesList) Schema() []fmt.Field { return nil }
func (s *NumericTypesList) Pointers() []any     { return nil }
func (s *NumericTypesList) Len() int             { return len(*s) }
func (s *NumericTypesList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *NumericTypesList) Append() fmt.Fielder  { v := &NumericTypes{}; *s = append(*s, v); return v }

func (m *NumericTypes) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func ReadOneNumericTypes(qb *orm.QB, model *NumericTypes) (*NumericTypes, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllNumericTypes(qb *orm.QB) (*NumericTypesList, error) {
	var results NumericTypesList
	err := qb.ReadAll(
		func() fmt.Model { return &NumericTypes{} },
		func(m fmt.Model) { results = append(results, m.(*NumericTypes)) },
	)
	return &results, err
}

func (m *RefNoColumn) ModelName() string {
	return "ref_no_column"
}

var _schemaRefNoColumn = []fmt.Field{
		{Name: "idref", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "parent_id", Type: fmt.FieldInt},
	}

func (m *RefNoColumn) Schema() []fmt.Field { return _schemaRefNoColumn }

func (m *RefNoColumn) Pointers() []any { return []any{&m.IDRef, &m.ParentID} }

type RefNoColumnList []*RefNoColumn

func (s *RefNoColumnList) Schema() []fmt.Field { return nil }
func (s *RefNoColumnList) Pointers() []any     { return nil }
func (s *RefNoColumnList) Len() int             { return len(*s) }
func (s *RefNoColumnList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *RefNoColumnList) Append() fmt.Fielder  { v := &RefNoColumn{}; *s = append(*s, v); return v }

func ReadOneRefNoColumn(qb *orm.QB, model *RefNoColumn) (*RefNoColumn, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRefNoColumn(qb *orm.QB) (*RefNoColumnList, error) {
	var results RefNoColumnList
	err := qb.ReadAll(
		func() fmt.Model { return &RefNoColumn{} },
		func(m fmt.Model) { results = append(results, m.(*RefNoColumn)) },
	)
	return &results, err
}

var _schemaPointerReceiver = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "name", Type: fmt.FieldText},
	}

func (m *PointerReceiver) Schema() []fmt.Field { return _schemaPointerReceiver }

func (m *PointerReceiver) Pointers() []any { return []any{&m.ID, &m.Name} }

type PointerReceiverList []*PointerReceiver

func (s *PointerReceiverList) Schema() []fmt.Field { return nil }
func (s *PointerReceiverList) Pointers() []any     { return nil }
func (s *PointerReceiverList) Len() int             { return len(*s) }
func (s *PointerReceiverList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *PointerReceiverList) Append() fmt.Fielder  { v := &PointerReceiver{}; *s = append(*s, v); return v }

func ReadOnePointerReceiver(qb *orm.QB, model *PointerReceiver) (*PointerReceiver, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPointerReceiver(qb *orm.QB) (*PointerReceiverList, error) {
	var results PointerReceiverList
	err := qb.ReadAll(
		func() fmt.Model { return &PointerReceiver{} },
		func(m fmt.Model) { results = append(results, m.(*PointerReceiver)) },
	)
	return &results, err
}

func (m *MockParent) ModelName() string {
	return "mock_parent"
}

var _schemaMockParent = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "name", Type: fmt.FieldText},
	}

func (m *MockParent) Schema() []fmt.Field { return _schemaMockParent }

func (m *MockParent) Pointers() []any { return []any{&m.ID, &m.Name} }

type MockParentList []*MockParent

func (s *MockParentList) Schema() []fmt.Field { return nil }
func (s *MockParentList) Pointers() []any     { return nil }
func (s *MockParentList) Len() int             { return len(*s) }
func (s *MockParentList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *MockParentList) Append() fmt.Fielder  { v := &MockParent{}; *s = append(*s, v); return v }

func ReadOneMockParent(qb *orm.QB, model *MockParent) (*MockParent, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMockParent(qb *orm.QB) (*MockParentList, error) {
	var results MockParentList
	err := qb.ReadAll(
		func() fmt.Model { return &MockParent{} },
		func(m fmt.Model) { results = append(results, m.(*MockParent)) },
	)
	return &results, err
}

func (m *MockChild) ModelName() string {
	return "mock_child"
}

var _schemaMockChild = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "mock_parent_id", Type: fmt.FieldText},
		{Name: "value", Type: fmt.FieldText},
	}

func (m *MockChild) Schema() []fmt.Field { return _schemaMockChild }

func (m *MockChild) Pointers() []any { return []any{&m.ID, &m.MockParentID, &m.Value} }

type MockChildList []*MockChild

func (s *MockChildList) Schema() []fmt.Field { return nil }
func (s *MockChildList) Pointers() []any     { return nil }
func (s *MockChildList) Len() int             { return len(*s) }
func (s *MockChildList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *MockChildList) Append() fmt.Fielder  { v := &MockChild{}; *s = append(*s, v); return v }

func ReadOneMockChild(qb *orm.QB, model *MockChild) (*MockChild, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMockChild(qb *orm.QB) (*MockChildList, error) {
	var results MockChildList
	err := qb.ReadAll(
		func() fmt.Model { return &MockChild{} },
		func(m fmt.Model) { results = append(results, m.(*MockChild)) },
	)
	return &results, err
}

// ReadAllMockChildByParentID retrieves all MockChild records for a given parent ID.
// Auto-generated by ormc — relation detected via db:"ref=mock_child".
func ReadAllMockChildByMockParentID(db *orm.DB, parentID string) (*MockChildList, error) {
	return ReadAllMockChild(db.Query(&MockChild{}).Where("mock_parent_id").Eq(parentID))
}

func (m *UserForm) ModelName() string {
	return "user_form"
}

var _schemaUserForm = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}, Widget: input.Text()},
		{Name: "name", Type: fmt.FieldText, Widget: input.Text(), Permitted: fmt.Permitted{Letters: true, Tilde: true, Spaces: true, Minimum: 2, Maximum: 100}},
		{Name: "email", Type: fmt.FieldText, NotNull: true, OmitEmpty: true, Widget: input.Email()},
		{Name: "password", Type: fmt.FieldText, NotNull: true, Widget: input.Password(), Permitted: fmt.Permitted{Minimum: 8}},
		{Name: "bio", Type: fmt.FieldText, OmitEmpty: true, Widget: input.Textarea(), Permitted: fmt.Permitted{Tilde: true, Spaces: true}},
		{Name: "age", Type: fmt.FieldInt, Widget: input.Number()},
	}

func (m *UserForm) Schema() []fmt.Field { return _schemaUserForm }

func (m *UserForm) Pointers() []any { return []any{&m.ID, &m.Name, &m.Email, &m.Password, &m.Bio, &m.Age} }

type UserFormList []*UserForm

func (s *UserFormList) Schema() []fmt.Field { return nil }
func (s *UserFormList) Pointers() []any     { return nil }
func (s *UserFormList) Len() int             { return len(*s) }
func (s *UserFormList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *UserFormList) Append() fmt.Fielder  { v := &UserForm{}; *s = append(*s, v); return v }

func (m *UserForm) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func ReadOneUserForm(qb *orm.QB, model *UserForm) (*UserForm, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserForm(qb *orm.QB) (*UserFormList, error) {
	var results UserFormList
	err := qb.ReadAll(
		func() fmt.Model { return &UserForm{} },
		func(m fmt.Model) { results = append(results, m.(*UserForm)) },
	)
	return &results, err
}

var _schemaLoginForm = []fmt.Field{
		{Name: "email", Type: fmt.FieldText, NotNull: true, Widget: input.Email()},
		{Name: "password", Type: fmt.FieldText, NotNull: true, Widget: input.Password()},
	}

func (m *LoginForm) Schema() []fmt.Field { return _schemaLoginForm }

func (m *LoginForm) Pointers() []any { return []any{&m.Email, &m.Password} }

type LoginFormList []*LoginForm

func (s *LoginFormList) Schema() []fmt.Field { return nil }
func (s *LoginFormList) Pointers() []any     { return nil }
func (s *LoginFormList) Len() int             { return len(*s) }
func (s *LoginFormList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *LoginFormList) Append() fmt.Fielder  { v := &LoginForm{}; *s = append(*s, v); return v }

func (m *LoginForm) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaTimeSlotResponse = []fmt.Field{
		{Name: "start_utc", Type: fmt.FieldInt, Widget: input.Number()},
		{Name: "end_utc", Type: fmt.FieldInt, Widget: input.Number()},
	}

func (m *TimeSlotResponse) Schema() []fmt.Field { return _schemaTimeSlotResponse }

func (m *TimeSlotResponse) Pointers() []any { return []any{&m.StartUTC, &m.EndUTC} }

type TimeSlotResponseList []*TimeSlotResponse

func (s *TimeSlotResponseList) Schema() []fmt.Field { return nil }
func (s *TimeSlotResponseList) Pointers() []any     { return nil }
func (s *TimeSlotResponseList) Len() int             { return len(*s) }
func (s *TimeSlotResponseList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *TimeSlotResponseList) Append() fmt.Fielder  { v := &TimeSlotResponse{}; *s = append(*s, v); return v }

func (m *TimeSlotResponse) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *Address) ModelName() string {
	return "address"
}

var _schemaAddress = []fmt.Field{
		{Name: "street", Type: fmt.FieldText},
		{Name: "city", Type: fmt.FieldText},
	}

func (m *Address) Schema() []fmt.Field { return _schemaAddress }

func (m *Address) Pointers() []any { return []any{&m.Street, &m.City} }

type AddressList []*Address

func (s *AddressList) Schema() []fmt.Field { return nil }
func (s *AddressList) Pointers() []any     { return nil }
func (s *AddressList) Len() int             { return len(*s) }
func (s *AddressList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *AddressList) Append() fmt.Fielder  { v := &Address{}; *s = append(*s, v); return v }

func ReadOneAddress(qb *orm.QB, model *Address) (*Address, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllAddress(qb *orm.QB) (*AddressList, error) {
	var results AddressList
	err := qb.ReadAll(
		func() fmt.Model { return &Address{} },
		func(m fmt.Model) { results = append(results, m.(*Address)) },
	)
	return &results, err
}

func (m *UserWithJSON) ModelName() string {
	return "user_with_json"
}

var _schemaUserWithJSON = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}, Widget: input.Text()},
		{Name: "name", Type: fmt.FieldText, Widget: input.Text()},
		{Name: "email", Type: fmt.FieldText, Widget: input.Email()},
		{Name: "bio", Type: fmt.FieldText, OmitEmpty: true, Widget: input.Textarea()},
		{Name: "home_addr", Type: fmt.FieldStruct},
	}

func (m *UserWithJSON) Schema() []fmt.Field { return _schemaUserWithJSON }

func (m *UserWithJSON) Pointers() []any { return []any{&m.ID, &m.Name, &m.Email, &m.Bio, &m.HomeAddr} }

type UserWithJSONList []*UserWithJSON

func (s *UserWithJSONList) Schema() []fmt.Field { return nil }
func (s *UserWithJSONList) Pointers() []any     { return nil }
func (s *UserWithJSONList) Len() int             { return len(*s) }
func (s *UserWithJSONList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *UserWithJSONList) Append() fmt.Fielder  { v := &UserWithJSON{}; *s = append(*s, v); return v }

func (m *UserWithJSON) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func ReadOneUserWithJSON(qb *orm.QB, model *UserWithJSON) (*UserWithJSON, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllUserWithJSON(qb *orm.QB) (*UserWithJSONList, error) {
	var results UserWithJSONList
	err := qb.ReadAll(
		func() fmt.Model { return &UserWithJSON{} },
		func(m fmt.Model) { results = append(results, m.(*UserWithJSON)) },
	)
	return &results, err
}

func (m *WithPointers) ModelName() string {
	return "with_pointers"
}

var _schemaWithPointers = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "addr", Type: fmt.FieldStruct},
	}

func (m *WithPointers) Schema() []fmt.Field { return _schemaWithPointers }

func (m *WithPointers) Pointers() []any { return []any{&m.ID, &m.Addr} }

type WithPointersList []*WithPointers

func (s *WithPointersList) Schema() []fmt.Field { return nil }
func (s *WithPointersList) Pointers() []any     { return nil }
func (s *WithPointersList) Len() int             { return len(*s) }
func (s *WithPointersList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *WithPointersList) Append() fmt.Fielder  { v := &WithPointers{}; *s = append(*s, v); return v }

func ReadOneWithPointers(qb *orm.QB, model *WithPointers) (*WithPointers, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWithPointers(qb *orm.QB) (*WithPointersList, error) {
	var results WithPointersList
	err := qb.ReadAll(
		func() fmt.Model { return &WithPointers{} },
		func(m fmt.Model) { results = append(results, m.(*WithPointers)) },
	)
	return &results, err
}

var _schemaMCPResponse = []fmt.Field{
		{Name: "result", Type: fmt.FieldRaw, Widget: input.Text()},
		{Name: "error", Type: fmt.FieldRaw, OmitEmpty: true, Widget: input.Text()},
	}

func (m *MCPResponse) Schema() []fmt.Field { return _schemaMCPResponse }

func (m *MCPResponse) Pointers() []any { return []any{&m.Result, &m.Error} }

type MCPResponseList []*MCPResponse

func (s *MCPResponseList) Schema() []fmt.Field { return nil }
func (s *MCPResponseList) Pointers() []any     { return nil }
func (s *MCPResponseList) Len() int             { return len(*s) }
func (s *MCPResponseList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *MCPResponseList) Append() fmt.Fielder  { v := &MCPResponse{}; *s = append(*s, v); return v }

func (m *MCPResponse) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaPlainResponse = []fmt.Field{
		{Name: "message", Type: fmt.FieldText, Widget: input.Text()},
		{Name: "code", Type: fmt.FieldText, OmitEmpty: true, Widget: input.Text()},
	}

func (m *PlainResponse) Schema() []fmt.Field { return _schemaPlainResponse }

func (m *PlainResponse) Pointers() []any { return []any{&m.Message, &m.Code} }

type PlainResponseList []*PlainResponse

func (s *PlainResponseList) Schema() []fmt.Field { return nil }
func (s *PlainResponseList) Pointers() []any     { return nil }
func (s *PlainResponseList) Len() int             { return len(*s) }
func (s *PlainResponseList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *PlainResponseList) Append() fmt.Fielder  { v := &PlainResponse{}; *s = append(*s, v); return v }

func (m *PlainResponse) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

