//go:build !wasm

package tests

import (
	"os"
	"strings"
	"testing"

	"github.com/tinywasm/orm"
)

func TestOrmc(t *testing.T) {
	t.Run("formonly directive", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("LoginForm", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for LoginForm: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		// MUST generate Fielder methods and FormName
		expectedStrings := []string{
			"func (m *LoginForm) FormName() string {",
			"func (m *LoginForm) Schema() []fmt.Field {",
			"func (m *LoginForm) Values() []any {",
			"func (m *LoginForm) Pointers() []any {",
		}
		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}

		// MUST NOT generate TableName or ORM helpers
		forbiddenStrings := []string{
			"func (m *LoginForm) TableName() string",
			"func ReadOneLoginForm",
			"func ReadAllLoginForm",
			"var LoginForm_ =",
			"\"github.com/tinywasm/orm\"", // Import should be missing
		}
		for _, forbidden := range forbiddenStrings {
			if strings.Contains(content, forbidden) {
				t.Errorf("Generated file contains forbidden string: %s", forbidden)
			}
		}
	})

	t.Run("Form tags and FormName", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("UserForm", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for UserForm: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			"func (m *UserForm) FormName() string {",
			"return \"user_form\"",
			"{Name: \"email\", Type: fmt.FieldText, NotNull: true, Input: \"email\"}",
			"{Name: \"password\", Type: fmt.FieldText, Input: \"password\"}",
			"{Name: \"bio\", Type: fmt.FieldText, Input: \"textarea\"}",
			"{Name: \"age\", Type: fmt.FieldInt, Input: \"-\"}",
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s\nContent:\n%s", expected, content)
			}
		}
	})

	t.Run("Generate User", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("User", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for User: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			// File may not be created if no fields are mappable
			if os.IsNotExist(err) {
				return
			}
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			"//go:build !wasm",
			"// DO NOT EDIT. generated by github.com/tinywasm/orm",
			"package tests",
			"func (m *User) TableName() string {",
			"return \"user\"",
			"func (m *User) FormName() string {",
			"return \"user\"",
			"func (m *User) Schema() []fmt.Field {",
			"{Name: \"id\", Type: fmt.FieldInt, PK: true}",
			"{Name: \"first_name\", Type: fmt.FieldText, NotNull: true}",
			"{Name: \"last_name\", Type: fmt.FieldText},",
			"{Name: \"email\", Type: fmt.FieldText, Unique: true}",
			"{Name: \"score\", Type: fmt.FieldFloat},",
			"{Name: \"is_active\", Type: fmt.FieldBool},",
			"{Name: \"avatar\", Type: fmt.FieldBlob},",
			"func (m *User) Values() []any {",
			"m.ID",
			"m.FirstName",
			"m.LastName",
			"func (m *User) Pointers() []any {",
			"&m.ID",
			"&m.FirstName",
			"&m.LastName",
			"var User_ = struct {",
			"TableName: \"user\"",
			"ID: \"id\"",
			"func ReadOneUser(qb *orm.QB, model *User) (*User, error) {",
			"func ReadAllUser(qb *orm.QB) ([]*User, error) {",
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}

		if strings.Contains(content, "\"age\"") || strings.Contains(content, "m.age") || strings.Contains(content, "&m.age") || strings.Contains(content, "Age:") {
			t.Errorf("Generated file should not contain unexported field 'age'")
		}
	})

	t.Run("Generate Order With Refs", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("Order", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for Order: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			if os.IsNotExist(err) {
				return
			}
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			"{Name: \"id\", Type: fmt.FieldText, PK: true}",
			"{Name: \"user_id\", Type: fmt.FieldInt},",
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}
	})

	t.Run("Bad Time Type — now a warning, not fatal", func(t *testing.T) {
		// D8: time.Time without db:"-" → warning + skip, not error
		err := orm.NewOrmc().GenerateForStruct("BadTimeNoTag", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Expected no error for time.Time (warn+skip), got: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		content, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		s := string(content)
		// CreatedAt must be absent (skipped)
		if strings.Contains(s, "CreatedAt") || strings.Contains(s, "created_at") {
			t.Error("time.Time field must be absent from generated output")
		}
		// ID and Name must be present
		if !strings.Contains(s, `"id"`) || !strings.Contains(s, `"name"`) {
			t.Error("Other fields must still be generated")
		}
	})

	t.Run("Bad AutoInc", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("BadAutoInc", "mock_generator_model.go")
		if err == nil || !strings.Contains(err.Error(), "autoincrement not allowed on FieldText") {
			t.Errorf("Expected error about autoincrement on FieldText, got %v", err)
		}
	})

	t.Run("Unsupported Type", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("Unsupp", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Did not expect error for unsupported type, got %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			if os.IsNotExist(err) {
				return
			}
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)
		if strings.Contains(content, "Ch") {
			t.Errorf("Expected 'Ch' to be absent in output, but it was generated")
		}
	})

	t.Run("Numeric Type Mapping and Bitmask", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("NumericTypes", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for NumericTypes: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			// int32 → FieldInt
			`{Name: "idnumeric", Type: fmt.FieldInt, PK: true, NotNull: true}`,
			// uint64 → FieldInt
			`{Name: "count_uint", Type: fmt.FieldInt},`,
			// float32 → FieldFloat
			`{Name: "ratio_f32", Type: fmt.FieldFloat},`,
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}
	})

	t.Run("Ref Without Column", func(t *testing.T) {
		err := orm.NewOrmc().GenerateForStruct("RefNoColumn", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for RefNoColumn: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		// Ref should NOT be in Input anymore
		if strings.Contains(content, `Input: "ref=parent"`) {
			t.Errorf("Ref should NOT be in Input anymore, got:\n%s", content)
		}
	})
}
