//go:build !wasm

package tests

import (
	"os"
	"strings"
	"testing"

	"github.com/tinywasm/orm"
)

func TestOrmc(t *testing.T) {
	t.Run("Generate User", func(t *testing.T) {
		err := orm.GenerateCodeForStruct("User", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for User: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			"// Code generated by ormc; DO NOT EDIT.",
			"// NOTE: Schema() and Values() must always be in the same field order.",
			"// String PK: set via github.com/tinywasm/unixid before calling db.Create().",
			"package tests",
			"func (m *User) TableName() string {",
			"return \"users\"",
			"func (m *User) Schema() []orm.Field {",
			"{Name: \"id\", Type: orm.TypeInt64, Constraints: orm.ConstraintPK}",
			"{Name: \"first_name\", Type: orm.TypeText, Constraints: orm.ConstraintNotNull}",
			"{Name: \"last_name\", Type: orm.TypeText, Constraints: orm.ConstraintNone}",
			"{Name: \"email\", Type: orm.TypeText, Constraints: orm.ConstraintUnique}",
			"{Name: \"score\", Type: orm.TypeFloat64, Constraints: orm.ConstraintNone}",
			"{Name: \"is_active\", Type: orm.TypeBool, Constraints: orm.ConstraintNone}",
			"{Name: \"avatar\", Type: orm.TypeBlob, Constraints: orm.ConstraintNone}",
			"func (m *User) Values() []any {",
			"m.ID",
			"m.FirstName",
			"m.LastName",
			"func (m *User) Pointers() []any {",
			"&m.ID",
			"&m.FirstName",
			"&m.LastName",
			"var UserMeta = struct {",
			"TableName: \"users\"",
			"ID: \"id\"",
			"func ReadOneUser(qb *orm.QB, model *User) (*User, error) {",
			"func ReadAllUser(qb *orm.QB) ([]*User, error) {",
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}

		if strings.Contains(content, "\"age\"") || strings.Contains(content, "m.age") || strings.Contains(content, "&m.age") || strings.Contains(content, "Age:") {
			t.Errorf("Generated file should not contain unexported field 'age'")
		}
	})

	t.Run("Generate Order With Refs", func(t *testing.T) {
		err := orm.GenerateCodeForStruct("Order", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for Order: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			"{Name: \"id\", Type: orm.TypeText, Constraints: orm.ConstraintPK}",
			"{Name: \"user_id\", Type: orm.TypeInt64, Constraints: orm.ConstraintNone, Ref: \"users\", RefColumn: \"id\"}",
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}
	})

	t.Run("Bad Time Type", func(t *testing.T) {
		err := orm.GenerateCodeForStruct("BadTime", "mock_generator_model.go")
		if err == nil || !strings.Contains(err.Error(), "time.Time not allowed") {
			t.Errorf("Expected error about time.Time, got %v", err)
		}
	})

	t.Run("Bad AutoInc", func(t *testing.T) {
		err := orm.GenerateCodeForStruct("BadAutoInc", "mock_generator_model.go")
		if err == nil || !strings.Contains(err.Error(), "autoincrement not allowed on TypeText") {
			t.Errorf("Expected error about autoincrement on TypeText, got %v", err)
		}
	})

	t.Run("Unsupported Type", func(t *testing.T) {
		err := orm.GenerateCodeForStruct("Unsupp", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Did not expect error for unsupported type, got %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)
		if strings.Contains(content, "Ch") {
			t.Errorf("Expected 'Ch' to be absent in output, but it was generated")
		}
	})

	t.Run("Numeric Type Mapping and Bitmask", func(t *testing.T) {
		err := orm.GenerateCodeForStruct("NumericTypes", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for NumericTypes: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		expectedStrings := []string{
			// int32 → TypeInt64
			`{Name: "idnumeric", Type: orm.TypeInt64, Constraints: orm.ConstraintPK | orm.ConstraintNotNull}`,
			// uint64 → TypeInt64
			`{Name: "count_uint", Type: orm.TypeInt64, Constraints: orm.ConstraintNone}`,
			// float32 → TypeFloat64
			`{Name: "ratio_f32", Type: orm.TypeFloat64, Constraints: orm.ConstraintNone}`,
		}

		for _, expected := range expectedStrings {
			if !strings.Contains(content, expected) {
				t.Errorf("Generated file missing expected string: %s", expected)
			}
		}

		// Bitmask correctness: ConstraintPK | ConstraintNotNull = 1 | 4 = 5
		pkConstraint := orm.ConstraintPK
		notNullConstraint := orm.ConstraintNotNull
		combined := pkConstraint | notNullConstraint
		if combined != 5 {
			t.Errorf("Expected ConstraintPK | ConstraintNotNull = 5, got %d", combined)
		}
	})

	t.Run("Ref Without Column", func(t *testing.T) {
		err := orm.GenerateCodeForStruct("RefNoColumn", "mock_generator_model.go")
		if err != nil {
			t.Fatalf("Failed to generate code for RefNoColumn: %v", err)
		}

		outFile := "mock_generator_model_orm.go"
		contentBytes, err := os.ReadFile(outFile)
		if err != nil {
			t.Fatalf("Failed to read generated file: %v", err)
		}
		defer os.Remove(outFile)

		content := string(contentBytes)

		// Ref present, RefColumn must be absent (empty string omitted from generated code)
		if !strings.Contains(content, `Ref: "parents"`) {
			t.Errorf("Expected Ref=parents in generated file")
		}
		if strings.Contains(content, "RefColumn") {
			t.Errorf("RefColumn must be absent when ref tag has no column")
		}
	})
}
