package tests

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestOrmGen(t *testing.T) {
	// Build the ormgen binary
	cmd := exec.Command("go", "build", "-o", "ormgen", "../cmd/ormgen")
	if err := cmd.Run(); err != nil {
		t.Fatalf("Failed to build ormgen: %v", err)
	}
	defer os.Remove("ormgen")

	// Set up environment to run ormgen programmatically
	absPath, err := filepath.Abs(".")
	if err != nil {
		t.Fatalf("Failed to get abs path: %v", err)
	}

	env := append(os.Environ(), "GOFILE=mock_generator_model.go")
	cmdGen := exec.Command(filepath.Join(absPath, "ormgen"), "-struct", "User")
	cmdGen.Env = env

	var out bytes.Buffer
	var stderr bytes.Buffer
	cmdGen.Stdout = &out
	cmdGen.Stderr = &stderr
	if err := cmdGen.Run(); err != nil {
		t.Fatalf("Failed to run ormgen: %v\nStderr: %s", err, stderr.String())
	}

	// Verify the output file exists
	outFile := "mock_generator_model_orm.go"
	contentBytes, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("Failed to read generated file: %v", err)
	}
	defer os.Remove(outFile)
	defer os.Remove("ormgen")

	content := string(contentBytes)

	// Assertions on generated content
	expectedStrings := []string{
		"// Code generated by ormgen; DO NOT EDIT.",
		"package tests",
		"func (m *User) TableName() string {",
		"return \"users\"",
		"func (m *User) Columns() []string {",
		"\"id\"",
		"\"first_name\"",
		"\"last_name\"",
		"\"email\"",
		"func (m *User) Values() []any {",
		"m.ID",
		"m.FirstName",
		"m.LastName",
		"m.Email",
		"func (m *User) Pointers() []any {",
		"&m.ID",
		"&m.FirstName",
		"&m.LastName",
		"&m.Email",
		"var UserMeta = struct {",
		"TableName: \"users\"",
		"ID: \"id\"",
		"FirstName: \"first_name\"",
		"LastName: \"last_name\"",
		"Email: \"email\"",
		"func ReadOneUser(qb *orm.QB, model *User) (*User, error) {",
		"func ReadAllUser(qb *orm.QB) ([]*User, error) {",
	}

	for _, expected := range expectedStrings {
		if !strings.Contains(content, expected) {
			t.Errorf("Generated file missing expected string: %s", expected)
		}
	}

	// Make sure unexported field 'age' is not there
	if strings.Contains(content, "\"age\"") || strings.Contains(content, "m.age") || strings.Contains(content, "&m.age") || strings.Contains(content, "Age:") {
		t.Errorf("Generated file should not contain unexported field 'age'")
	}
}
