//go:build !wasm
// DO NOT EDIT. generated by github.com/tinywasm/orm

package mcporm

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *QueryArgs) ModelName() string {
	return "query_args"
}

var _schemaQueryArgs = []fmt.Field{
		{Name: "sql", Type: fmt.FieldText, NotNull: true},
		{Name: "args", Type: fmt.FieldText},
	}

func (m *QueryArgs) Schema() []fmt.Field { return _schemaQueryArgs }

func (m *QueryArgs) Pointers() []any { return []any{&m.SQL, &m.Args} }

type QueryArgsList []*QueryArgs

func (s *QueryArgsList) Schema() []fmt.Field { return nil }
func (s *QueryArgsList) Pointers() []any     { return nil }
func (s *QueryArgsList) Len() int             { return len(*s) }
func (s *QueryArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *QueryArgsList) Append() fmt.Fielder  { v := &QueryArgs{}; *s = append(*s, v); return v }

func (m *QueryArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func ReadOneQueryArgs(qb *orm.QB, model *QueryArgs) (*QueryArgs, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllQueryArgs(qb *orm.QB) (*QueryArgsList, error) {
	var results QueryArgsList
	err := qb.ReadAll(
		func() fmt.Model { return &QueryArgs{} },
		func(m fmt.Model) { results = append(results, m.(*QueryArgs)) },
	)
	return &results, err
}

func (m *ExecArgs) ModelName() string {
	return "exec_args"
}

var _schemaExecArgs = []fmt.Field{
		{Name: "sql", Type: fmt.FieldText, NotNull: true},
		{Name: "args", Type: fmt.FieldText},
	}

func (m *ExecArgs) Schema() []fmt.Field { return _schemaExecArgs }

func (m *ExecArgs) Pointers() []any { return []any{&m.SQL, &m.Args} }

type ExecArgsList []*ExecArgs

func (s *ExecArgsList) Schema() []fmt.Field { return nil }
func (s *ExecArgsList) Pointers() []any     { return nil }
func (s *ExecArgsList) Len() int             { return len(*s) }
func (s *ExecArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *ExecArgsList) Append() fmt.Fielder  { v := &ExecArgs{}; *s = append(*s, v); return v }

func (m *ExecArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func ReadOneExecArgs(qb *orm.QB, model *ExecArgs) (*ExecArgs, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllExecArgs(qb *orm.QB) (*ExecArgsList, error) {
	var results ExecArgsList
	err := qb.ReadAll(
		func() fmt.Model { return &ExecArgs{} },
		func(m fmt.Model) { results = append(results, m.(*ExecArgs)) },
	)
	return &results, err
}
