
package ormc

import (
	"os"

	"github.com/tinywasm/fmt"
)

// GenerateForFile writes ORM implementations for all infos into one file.
func (o *Generator) GenerateForFile(infos []StructInfo, sourceFile string) error {
	if len(infos) == 0 {
		return nil
	}
	buf := fmt.Convert()

	// File Header
	buf.Write(fmt.Sprintf("// DO NOT EDIT. generated by github.com/tinywasm/orm\n\n"))
	buf.Write(fmt.Sprintf("package %s\n\n", infos[0].PackageName))

	hasModel := false
	hasWidget := false
	for _, info := range infos {
		if !info.NoDB {
			hasModel = true
		}
		for _, f := range info.Fields {
			if f.WidgetConstructor != "" {
				hasWidget = true
			}
		}
	}

	buf.Write("import (\n")
	buf.Write("\t\"github.com/tinywasm/fmt\"\n")
	if hasModel {
		buf.Write("\t\"github.com/tinywasm/orm\"\n")
	}
	if hasWidget {
		buf.Write("\t\"github.com/tinywasm/form/input\"\n")
	}
	buf.Write(")\n\n")

	for _, info := range infos {
		// Model Interface Methods
		if !info.ModelNameDeclared {
			buf.Write(fmt.Sprintf("func (m *%s) ModelName() string {\n", info.Name))
			buf.Write(fmt.Sprintf("\treturn \"%s\"\n", info.ModelName))
			buf.Write("}\n\n")
		}

		buf.Write(fmt.Sprintf("var _schema%s = []fmt.Field{\n", info.Name))
		for _, f := range info.Fields {
			typeStr := "fmt.FieldText"
			switch f.Type {
			case fmt.FieldInt:
				typeStr = "fmt.FieldInt"
			case fmt.FieldFloat:
				typeStr = "fmt.FieldFloat"
			case fmt.FieldBool:
				typeStr = "fmt.FieldBool"
			case fmt.FieldBlob:
				typeStr = "fmt.FieldBlob"
			case fmt.FieldStruct:
				typeStr = "fmt.FieldStruct"
			case fmt.FieldRaw:
				typeStr = "fmt.FieldRaw"
			case fmt.FieldIntSlice:
				typeStr = "fmt.FieldIntSlice"
			case fmt.FieldStructSlice:
				typeStr = "fmt.FieldStructSlice"
			}

			buf.Write(fmt.Sprintf("\t\t{Name: \"%s\", Type: %s", f.ColumnName, typeStr))
			if !info.NoDB && (f.PK || f.Unique || f.AutoInc) {
				buf.Write(", DB: &fmt.FieldDB{")
				var parts []string
				if f.PK {
					parts = append(parts, "PK: true")
				}
				if f.Unique {
					parts = append(parts, "Unique: true")
				}
				if f.AutoInc {
					parts = append(parts, "AutoInc: true")
				}
				buf.Write(fmt.Convert(parts).Join(", ").String())
				buf.Write("}")
			}
			if f.NotNull {
				buf.Write(", NotNull: true")
			}
			if f.OmitEmpty {
				buf.Write(", OmitEmpty: true")
			}
			if f.WidgetConstructor != "" {
				widgetExpr := f.WidgetConstructor
				for _, tag := range f.Tags {
					if wrapper, ok := tagSetters[tag]; ok {
						widgetExpr = fmt.Sprintf(wrapper, widgetExpr)
					}
				}
				buf.Write(fmt.Sprintf(", Widget: %s", widgetExpr))
			}
			writePermittedFields(buf, f)
			buf.Write("},\n")
		}
		buf.Write("\t}\n\n")

		buf.Write(fmt.Sprintf("func (m *%s) Schema() []fmt.Field { return _schema%s }\n\n", info.Name, info.Name))

		buf.Write(fmt.Sprintf("func (m *%s) Pointers() []any { return []any{", info.Name))
		for i, f := range info.Fields {
			if i > 0 {
				buf.Write(", ")
			}
			buf.Write(fmt.Sprintf("&m.%s", f.Name))
		}
		buf.Write("} }\n\n")

		buf.Write(fmt.Sprintf("func (m *%s) IsNil() bool { return m == nil }\n\n", info.Name))

		buf.Write(fmt.Sprintf("func (m *%s) EncodeFields(w fmt.FieldWriter) {\n", info.Name))
		for _, f := range info.Fields {
			var line string
			switch f.Type {
			case fmt.FieldText:
				line = fmt.Sprintf("w.String(\"%s\", m.%s)", f.ColumnName, f.Name)
			case fmt.FieldRaw:
				line = fmt.Sprintf("w.Raw(\"%s\", m.%s)", f.ColumnName, f.Name)
			case fmt.FieldInt:
				line = fmt.Sprintf("w.Int(\"%s\", int64(m.%s))", f.ColumnName, f.Name)
			case fmt.FieldFloat:
				line = fmt.Sprintf("w.Float(\"%s\", float64(m.%s))", f.ColumnName, f.Name)
			case fmt.FieldBool:
				line = fmt.Sprintf("w.Bool(\"%s\", m.%s)", f.ColumnName, f.Name)
			case fmt.FieldBlob:
				line = fmt.Sprintf("w.Bytes(\"%s\", m.%s)", f.ColumnName, f.Name)
			case fmt.FieldStruct:
				if f.IsPointer {
					if f.OmitEmpty {
						line = fmt.Sprintf("w.Object(\"%s\", m.%s)", f.ColumnName, f.Name)
					} else {
						buf.Write(fmt.Sprintf("\tif m.%s != nil { w.Object(\"%s\", m.%s) } else { w.Null(\"%s\") }\n", f.Name, f.ColumnName, f.Name, f.ColumnName))
					}
				} else {
					line = fmt.Sprintf("w.Object(\"%s\", &m.%s)", f.ColumnName, f.Name)
				}
			case fmt.FieldIntSlice:
				if f.OmitEmpty {
					buf.Write(fmt.Sprintf("\tif len(m.%s) != 0 {\n", f.Name))
				}
				buf.Write(fmt.Sprintf("\t\t{\n\t\t\tarr := w.Array(\"%s\", len(m.%s))\n\t\t\tfor _, x := range m.%s {\n\t\t\t\tarr.Int(int64(x))\n\t\t\t}\n\t\t\tarr.Close()\n\t\t}\n", f.ColumnName, f.Name, f.Name))
				if f.OmitEmpty {
					buf.Write("\t}\n")
				}
			case fmt.FieldStructSlice:
				isPtr := fmt.HasPrefix(f.GoType, "[]*")
				if f.OmitEmpty {
					buf.Write(fmt.Sprintf("\tif len(m.%s) != 0 {\n", f.Name))
				}
				buf.Write(fmt.Sprintf("\t\t{\n\t\t\tarr := w.Array(\"%s\", len(m.%s))\n\t\t\tfor _, x := range m.%s {\n", f.ColumnName, f.Name, f.Name))
				if isPtr {
					buf.Write("\t\t\t\tif x != nil { arr.Object(x) }\n")
				} else {
					buf.Write("\t\t\t\tarr.Object(&x)\n")
				}
				buf.Write("\t\t\t}\n\t\t\tarr.Close()\n\t\t}\n")
				if f.OmitEmpty {
					buf.Write("\t}\n")
				}
			}

			if f.OmitEmpty && line != "" {
				guard := ""
				switch f.Type {
				case fmt.FieldText:
					guard = fmt.Sprintf("m.%s != \"\"", f.Name)
				case fmt.FieldRaw, fmt.FieldBlob:
					guard = fmt.Sprintf("len(m.%s) != 0", f.Name)
				case fmt.FieldInt, fmt.FieldFloat:
					guard = fmt.Sprintf("m.%s != 0", f.Name)
				case fmt.FieldBool:
					guard = fmt.Sprintf("m.%s", f.Name)
				case fmt.FieldStruct:
					if f.IsPointer {
						guard = fmt.Sprintf("m.%s != nil", f.Name)
					}
				}
				if guard != "" {
					buf.Write(fmt.Sprintf("\tif %s { %s }\n", guard, line))
					continue
				}
			}
			if line != "" {
				buf.Write("\t" + line + "\n")
			}
		}
		buf.Write("}\n\n")

		buf.Write(fmt.Sprintf("func (m *%s) DecodeFields(r fmt.FieldReader) {\n", info.Name))
		for _, f := range info.Fields {
			switch f.Type {
			case fmt.FieldText:
				buf.Write(fmt.Sprintf("\tif v, ok := r.String(\"%s\"); ok { m.%s = v }\n", f.ColumnName, f.Name))
			case fmt.FieldRaw:
				buf.Write(fmt.Sprintf("\tif v, ok := r.Raw(\"%s\"); ok { m.%s = v }\n", f.ColumnName, f.Name))
			case fmt.FieldInt:
				buf.Write(fmt.Sprintf("\tif v, ok := r.Int(\"%s\"); ok { m.%s = %s(v) }\n", f.ColumnName, f.Name, f.GoType))
			case fmt.FieldFloat:
				buf.Write(fmt.Sprintf("\tif v, ok := r.Float(\"%s\"); ok { m.%s = %s(v) }\n", f.ColumnName, f.Name, f.GoType))
			case fmt.FieldBool:
				buf.Write(fmt.Sprintf("\tif v, ok := r.Bool(\"%s\"); ok { m.%s = v }\n", f.ColumnName, f.Name))
			case fmt.FieldBlob:
				buf.Write(fmt.Sprintf("\tif v, ok := r.Bytes(\"%s\"); ok { m.%s = v }\n", f.ColumnName, f.Name))
			case fmt.FieldStruct:
				elemType := f.GoType
				if f.IsPointer {
					buf.Write(fmt.Sprintf("\tif m.%s == nil { m.%s = new(%s) }\n", f.Name, f.Name, elemType))
					buf.Write(fmt.Sprintf("\tif !r.Object(\"%s\", m.%s) { m.%s = nil }\n", f.ColumnName, f.Name, f.Name))
				} else {
					buf.Write(fmt.Sprintf("\tr.Object(\"%s\", &m.%s)\n", f.ColumnName, f.Name))
				}
			case fmt.FieldIntSlice:
				elemType := fmt.Convert(f.GoType).TrimPrefix("[]").String()
				buf.Write(fmt.Sprintf("\tif arr, ok := r.Array(\"%s\"); ok {\n", f.ColumnName))
				buf.Write(fmt.Sprintf("\t\tn := arr.Len()\n\t\tm.%s = make(%s, n)\n\t\tfor i := 0; i < n; i++ {\n\t\t\tm.%s[i] = %s(arr.Int(i))\n\t\t}\n\t}\n", f.Name, f.GoType, f.Name, elemType))
			case fmt.FieldStructSlice:
				isPtr := fmt.HasPrefix(f.GoType, "[]*")
				elemType := fmt.Convert(f.GoType).TrimPrefix("[]").TrimPrefix("*").String()
				buf.Write(fmt.Sprintf("\tif arr, ok := r.Array(\"%s\"); ok {\n", f.ColumnName))
				buf.Write(fmt.Sprintf("\t\tn := arr.Len()\n\t\tm.%s = make(%s, n)\n\t\tfor i := 0; i < n; i++ {\n", f.Name, f.GoType))
				if isPtr {
					buf.Write(fmt.Sprintf("\t\t\tm.%s[i] = new(%s)\n", f.Name, elemType))
					buf.Write(fmt.Sprintf("\t\t\tarr.Object(i, m.%s[i])\n", f.Name))
				} else {
					buf.Write(fmt.Sprintf("\t\t\tarr.Object(i, &m.%s[i])\n", f.Name))
				}
				buf.Write("\t\t}\n\t}\n")
			}
		}
		buf.Write("}\n\n")

		// RenameProvider
		hasOldNames := false
		for _, f := range info.Fields {
			if f.OldName != "" {
				hasOldNames = true
				break
			}
		}
		if hasOldNames {
			buf.Write(fmt.Sprintf("func (m *%s) OldNames() map[string]string {\n", info.Name))
			buf.Write("\treturn map[string]string{\n")
			for _, f := range info.Fields {
				if f.OldName != "" {
					buf.Write(fmt.Sprintf("\t\t\"%s\": \"%s\",\n", f.ColumnName, f.OldName))
				}
			}
			buf.Write("\t}\n}\n\n")
		}

		buf.Write(fmt.Sprintf("type %sList []*%s\n\n", info.Name, info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) Schema() []fmt.Field { return nil }\n", info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) Pointers() []any     { return nil }\n", info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) Len() int             { return len(*s) }\n", info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) At(i int) fmt.Fielder { return (*s)[i] }\n", info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) Append() fmt.Fielder  { v := &%s{}; *s = append(*s, v); return v }\n", info.Name, info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) IsNil() bool          { return s == nil }\n", info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) EncodeFields(_ fmt.FieldWriter) {}\n", info.Name))
		buf.Write(fmt.Sprintf("func (s *%sList) DecodeFields(_ fmt.FieldReader) {}\n\n", info.Name))

		hasValidation := info.IsForm
		if !hasValidation {
			for _, f := range info.Fields {
				if f.NotNull || f.Letters || f.Numbers || f.Tilde || f.Spaces ||
					len(f.Extra) > 0 || f.Minimum > 0 || f.Maximum > 0 {
					hasValidation = true
					break
				}
			}
		}

		if hasValidation {
			buf.Write(fmt.Sprintf("func (m *%s) Validate(action byte) error {\n", info.Name))
			buf.Write("\treturn fmt.ValidateFields(action, m)\n")
			buf.Write("}\n\n")
		}

		if !info.NoDB {
			// Metadata Descriptors
			if info.WantTypedFields {
				buf.Write(fmt.Sprintf("var %s_ = struct {\n", info.Name))
				for _, f := range info.Fields {
					buf.Write(fmt.Sprintf("\t%s string\n", f.Name))
				}
				buf.Write("}{\n")
				for _, f := range info.Fields {
					buf.Write(fmt.Sprintf("\t%s: \"%s\",\n", f.Name, f.ColumnName))
				}
				buf.Write("}\n\n")
			}

			// Typed Read Operations
			buf.Write(fmt.Sprintf("func ReadOne%s(qb *orm.QB, model *%s) (*%s, error) {\n", info.Name, info.Name, info.Name))
			buf.Write("\terr := qb.ReadOne()\n")
			buf.Write("\tif err != nil {\n")
			buf.Write("\t\treturn nil, err\n")
			buf.Write("\t}\n")
			buf.Write("\treturn model, nil\n")
			buf.Write("}\n\n")

			buf.Write(fmt.Sprintf("func ReadAll%s(qb *orm.QB) (*%sList, error) {\n", info.Name, info.Name))
			buf.Write(fmt.Sprintf("\tvar results %sList\n", info.Name))
			buf.Write("\terr := qb.ReadAll(\n")
			buf.Write(fmt.Sprintf("\t\tfunc() fmt.Model { return &%s{} },\n", info.Name))
			buf.Write(fmt.Sprintf("\t\tfunc(m fmt.Model) { results = append(results, m.(*%s)) },\n", info.Name))
			buf.Write("\t)\n")
			buf.Write("\treturn &results, err\n")
			buf.Write("}\n\n")

			for _, rel := range info.Relations {
				where := fmt.Sprintf("\"%s\"", rel.FKColumn)
				if rel.UseFieldDescriptor {
					where = fmt.Sprintf("%s_.%s", rel.ChildStruct, rel.FKField)
				}
				buf.Write(fmt.Sprintf(
					"// ReadAll%sByParentID retrieves all %s records for a given parent ID.\n"+
						"// Auto-generated by ormc — relation detected via db:\"ref=%s\".\n"+
						"func ReadAll%sBy%s(db *orm.DB, parentID %s) (*%sList, error) {\n"+
						"\treturn ReadAll%s(db.Query(&%s{}).Where(%s).Eq(parentID))\n"+
						"}\n\n",
					rel.ChildStruct,
					rel.ChildStruct,
					info.ModelName, // parent table, for the comment
					rel.ChildStruct, rel.FKField, rel.FKFieldType,
					rel.ChildStruct,
					rel.ChildStruct, rel.ChildStruct, where,
				))
			}
		}
	}

	outName := fmt.Convert(sourceFile).TrimSuffix(".go").String() + "_orm.go"
	return os.WriteFile(outName, buf.Bytes(), 0644)
}
