package ormc

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/tinywasm/fmt"
)

func TestParseGenerated(t *testing.T) {
	// MS1: parseGenerated on a local fixture *_orm.go
	content := `// DO NOT EDIT. generated by github.com/tinywasm/orm
package test

import "github.com/tinywasm/fmt"

func (m *CatalogItem) ModelName() string {
	return "catalog_item"
}

var _schemaCatalogItem = []fmt.Field{
	{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
	{Name: "name", Type: fmt.FieldText, NotNull: true},
	{Name: "price", Type: fmt.FieldInt},
	{Name: "active", Type: fmt.FieldBool},
}

func (m *CatalogItem) Schema() []fmt.Field { return _schemaCatalogItem }
func (m *CatalogItem) Pointers() []any { return nil }
`
	tmpDir, _ := os.MkdirTemp("", "ormc_test")
	defer os.RemoveAll(tmpDir)

	path := filepath.Join(tmpDir, "item_orm.go")
	os.WriteFile(path, []byte(content), 0644)

	schemas, err := parseGenerated(path)
	if err != nil {
		t.Fatal(err)
	}

	fields, ok := schemas["catalog_item"]
	if !ok {
		t.Fatal("table catalog_item not found")
	}

	if len(fields) != 4 {
		t.Fatalf("expected 4 fields, got %d", len(fields))
	}

	if fields[0].Name != "id" || fields[0].Type != fmt.FieldText || fields[0].DB == nil || !fields[0].DB.PK {
		t.Errorf("field 0 mismatch: %+v", fields[0])
	}

	if fields[1].Name != "name" || !fields[1].NotNull {
		t.Errorf("field 1 mismatch: %+v", fields[1])
	}
}

func TestParseGenerated_MS2(t *testing.T) {
	// MS2: parseGenerated PK/Unique/AutoInc
	content := `package test
import "github.com/tinywasm/fmt"

func (m *User) ModelName() string { return "users" }
var _schemaUser = []fmt.Field{
	{Name: "id", Type: fmt.FieldInt, DB: &fmt.FieldDB{PK: true, AutoInc: true}},
	{Name: "email", Type: fmt.FieldText, DB: &fmt.FieldDB{Unique: true}},
}
`
	tmpDir, _ := os.MkdirTemp("", "ormc_test")
	defer os.RemoveAll(tmpDir)

	path := filepath.Join(tmpDir, "user_orm.go")
	os.WriteFile(path, []byte(content), 0644)

	schemas, err := parseGenerated(path)
	if err != nil {
		t.Fatal(err)
	}

	fields := schemas["users"]
	if !fields[0].DB.PK || !fields[0].DB.AutoInc {
		t.Errorf("id field DB mismatch: %+v", fields[0].DB)
	}
	if !fields[1].DB.Unique {
		t.Errorf("email field DB mismatch: %+v", fields[1].DB)
	}
}

func TestParseGenerated_MS7(t *testing.T) {
	// MS7: unknown fmt.FieldXxx in literal
	content := `package test
import "github.com/tinywasm/fmt"

func (m *X) ModelName() string { return "x" }
var _schemaX = []fmt.Field{
	{Name: "a", Type: fmt.FieldText},
	{Name: "b", Type: fmt.FieldUnknown},
}
`
	tmpDir, _ := os.MkdirTemp("", "ormc_test")
	defer os.RemoveAll(tmpDir)

	path := filepath.Join(tmpDir, "x_orm.go")
	os.WriteFile(path, []byte(content), 0644)

	schemas, err := parseGenerated(path)
	if err != nil {
		t.Fatal(err)
	}

	fields := schemas["x"]
	if len(fields) != 2 {
		t.Fatal("expected 2 fields")
	}
	if fields[1].Type != 0 {
		t.Errorf("expected 0 for unknown type, got %v", fields[1].Type)
	}
}
